#!/bin/bash
#

# Keep stock CM10.2 kernel up-to-date
cd ~/android/aokp/bootable/recovery
git checkout stock

# Sync CM10.1 phone sources
cd ~/android/aokp/
repo sync -j8

# Return to mackay kernel
cd ~/android/aokp/bootable/recovery
git checkout mackay-cm102

