#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set version info:
rn=Mackay_ROM
rv=1.4.3
kn=Mackay_kernel
kv=0.90
s2rv=$rv-s2
p970rv=$rv-p970
p4wifirv=$rv-p4wifi

#****************************************************************
## Check for missing parameters:

if [ "$1" != "s"  ] && [ "$1" != "s2"  ] && [ "$1" != "p970"  ] && [ "$1" != "p4wifi"  ]
then
  echo "No target device defined"
  exit 0
fi

if [ "$2" != "r"  ] && [ "$2" != "r4k"  ] && [ "$2" != "k"  ] && [ "$2" != "4k"  ] && [ "$2" != "bln"  ]
then
  echo "No build specification defined"
  exit 0
fi

#****************************************************************
## Set basic parameters:

if [ "$1" = "s" ]
then
target=galaxysmtd
fi

if [ "$1" = "s2" ]
then
target=i9100
fi

if [ "$1" = "p970" ]
then
target=p970
fi

if [ "$1" = "p4wifi" ]
then
target=p4wifi
fi

out=~/android/system/out/target/product/$target
top=~/android/system
sec=~/android/system/build/target/product/security

if [ "$target" = "galaxysmtd" ]  &&  [ "$2" = "r" ]
then
echo "A rom and stock kernel will be build for $target"
s-cm10 "${target}" "${out}" "${top}" "${sec}" "${rn}" "${rv}" "${kn}" "${kv}"
fi

if [ "$target" = "galaxysmtd" ]  &&  [ "$2" = "r4k" ]
then
echo "A rom and all four kernels will be build for $target"
s-cm10-4k "${target}" "${out}" "${top}" "${sec}" "${rn}" "${rv}" "${kn}" "${kv}"
fi

if [ "$target" = "galaxysmtd" ]  &&  [ "$2" = "k" ]
then
echo "A stock kernel will be build for $target"
s-kernel "${target}" "${out}" "${kn}" "${kv}"
fi

if [ "$target" = "galaxysmtd" ]  &&  [ "$2" = "4k" ]
then
echo "All four kernel flavours will be build for $target"
s-4kernels "${target}" "${out}" "${kn}" "${kv}"
fi

if [ "$target" = "i9100"  ]  &&  [ "$2" = "r" ]
then
echo "A rom and stock kernel will be build for $target"
s2-cm10 "${target}" "${out}" "${top}" "${sec}" "${rn}" "${s2rv}"
fi

if [ "$target" = "p970"  ]  &&  [ "$2" = "r" ]
then
echo "A rom will be build for $target"
p970-cm10 "${target}" "${out}" "${top}" "${sec}" "${rn}" "${p970rv}"
fi

if [ "$target" = "p4wifi"  ]  &&  [ "$2" = "r" ]
then
echo "A rom will be build for $target"
p4wifi-cm10 "${target}" "${out}" "${top}" "${sec}" "${rn}" "${p4wifirv}"
fi
