#!/bin/bash
#

#****************************************************************
## Set basic parameters:
version=$1
trgt=$2
finalout=$3
androidtop=$4
secsign=$5

#****************************************************************
## Clean build environment:
cd $androidtop
make clean
rm $finalout/recovery.img

#****************************************************************
## Build the recovery:
cd $androidtop
. build/envsetup.sh
breakfast $trgt
mka recoveryimage

#****************************************************************
## Check whether Signapk.jar needs to be build:
if [ ! -e $androidtop/out/host/linux-x86/framework/signapk.jar ]
then
  echo "Signapk.jar not found, rebuilding..."
  mka signapk
fi

#****************************************************************
## Finish off the kernel by packing it in a zip:
build_recovery_p_finalize "${version}" "${trgt}" "${finalout}" "${androidtop}" "${secsign}"
