#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set basic parameters here:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4
romname=$5
romversion=$6
cmversion=$7

#****************************************************************
## Checkout correct recovery:
if [ "$cmversion" = "cm10" ]
then
  cd $androidtop/bootable/recovery
  git checkout mackay
fi
if [ "$cmversion" = "cm101" ]
then
  cd $androidtop/bootable/recovery
  git checkout mackay-cm101
fi

#****************************************************************
## Checkout correct kernel:
if [ "$trgt" = "p970"  ]  &&  [ "$cmversion" = "cm101" ]
then
  cd $androidtop/kernel/lge/p970
  git checkout mackay-cm101
fi
if [ "$trgt" = "i9100"  ]  &&  [ "$cmversion" = "cm101" ]
then
  cd $androidtop/kernel/samsung/smdk4210
  git checkout mackay-cm101
fi

#****************************************************************
## Clean environment:
cd $androidtop
make installclean
rm $finalout/system/build.prop
rm $finalout/obj/PACKAGING/target_files_intermediates/cm_$trgt-target_files-eng.kasper.zip
rm $finalout/obj/PACKAGING/target_files_intermediates/cm_$trgt-target_files-eng.kasper/SYSTEM/build.prop

#****************************************************************
## Set ROM version in common.mk:
cd $androidtop/vendor/cm
sed "/Mackay/c\    CM_VERSION := `echo $romname`_`echo $romversion`" $androidtop/vendor/cm/config/common.mk > $androidtop/vendor/cm/config/common.updated
mv $androidtop/vendor/cm/config/common.updated $androidtop/vendor/cm/config/common.mk
git add config/common.mk
git commit -m "Bump ROM version to `echo $romversion`"

#****************************************************************
## Make the build:
cd $androidtop/
. build/envsetup.sh && brunch $trgt

#****************************************************************
## Finish off the ROM by packing in gapps & updated script:
build_rom_finalize "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${romname}" "${romversion}" "${cmversion}"

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
