#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set basic parameters here:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4
romname=$5
romversion=$6
kernelname=$7
kernelversion=$8

#****************************************************************
## Checkout correct recovery:
cd $androidtop/bootable/recovery
git checkout mackay-cm101

#****************************************************************
## Checkout correct kernel:
if [ "$trgt" = "p970"  ]
then
  cd $androidtop/kernel/lge/p970
  git checkout mackay-cm101
fi
if [ "$trgt" = "i9100"  ]
then
  cd $androidtop/kernel/samsung/smdk4210
  git checkout mackay-cm101
fi
if [ "$trgt" = "i9100"  ]
then
  cd $androidtop/kernel/samsung/aries
  sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`")\"" $androidtop/kernel/samsung/aries/init/version.c > $androidtop/kernel/samsung/aries/init/version.vc
  mv $androidtop/kernel/samsung/aries/init/version.vc $androidtop/kernel/samsung/aries/init/version.c
  git add init/version.c
  git commit -m "Bump kernel version to `echo $kernelversion`"
fi

#****************************************************************
## Clean environment:
cd $androidtop
make installclean
rm $finalout/system/build.prop
rm $finalout/obj/PACKAGING/target_files_intermediates/cm_$trgt-target_files-eng.kasper.zip
rm $finalout/obj/PACKAGING/target_files_intermediates/cm_$trgt-target_files-eng.kasper/SYSTEM/build.prop

#****************************************************************
## Set ROM version in common.mk:
cd $androidtop/vendor/cm
sed "/Mackay/c\    CM_VERSION := `echo $romname`_`echo $romversion`" $androidtop/vendor/cm/config/common.mk > $androidtop/vendor/cm/config/common.updated
mv $androidtop/vendor/cm/config/common.updated $androidtop/vendor/cm/config/common.mk

#****************************************************************
## Make the build:
cd $androidtop/
. build/envsetup.sh && brunch $trgt

cd $androidtop/vendor/cm
git reset --hard
cd $androidtop

#****************************************************************
## Check whether build finished succesfully:
echo "Check whether the build finished succesfully"
if [ -e $finalout/cm-`echo $romname`_`echo $romversion`.zip ]
then
  echo "Build finished succesfully"
else
  echo "Build not found, probably a compile error occured"
  exit 0
fi

#****************************************************************
## Move the ROM to the final ROM preparation stage:
mv $finalout/cm-`echo $romname`* ~/android/scripts/finalize_rom

#****************************************************************
## Set name of final file:
zipname=CM-`echo $romname`-`echo $romversion`-cm101

#****************************************************************
## Execute the final ROM preparation:
cd ~/android/scripts/finalize_rom
rm *.md5sum
echo "Extracting Mackay ROM"
unzip -q cm-`echo $romname`* -d MackayExtract

if [ "$trgt" = "galaxysmtd"  ]
  then
    cp updater-script_clean_$trgt updater-script
    cp updater-script MackayExtract/META-INF/com/google/android
    rm updater-script
    echo "Repacking a clean Mackay ROM"
    cd MackayExtract
    zip -qr ../`echo $zipname`-clean.zip ./
    cd ..
    echo "Copying fininalized clean build to AndroidFlash directory"
    mv `echo $zipname`-clean.zip ~/AndroidFlash/$trgt
fi

echo "Copying the updater-script for $trgt"
cp updater-script_$trgt updater-script

cp updater-script MackayExtract/META-INF/com/google/android
rm updater-script

echo "Copying Gapps"
cp -R gapps/system/* MackayExtract/system

echo "Removing QuickSearchBox & VideoEditor for $trgt"
rm MackayExtract/system/app/VideoEditor.apk
rm -rf MackayExtract/system/media/video
rm MackayExtract/system/app/QuickSearchBox.apk

echo "Repacking Mackay ROM"
cd MackayExtract
zip -qr ../`echo $zipname`-full.zip ./
cd ..

echo "Copying fininalized build to AndroidFlash directory"
mv `echo $zipname`-full.zip ~/AndroidFlash/$trgt

echo "Cleaning environment"
rm -r MackayExtract
rm cm-$romname*
cd $androidtop

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
