#!/bin/bash
#

#****************************************************************
## Set basic parameters:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4
romname=$5
romversion=$6
cmversion=$7

#****************************************************************
## Check whether build finished succesfully:
echo "Check whether $cmversion-based build finished succesfully"
if [ -e $finalout/`echo $romname`_`echo $romversion`.zip ]
then
  echo "Build finished succesfully"
else
  echo "Build not found, probably a compile error occured"
  exit 0
fi

#****************************************************************
## Choose correct finalizing folder:
if [ "$trgt" = "p4wifi"  ] && [ "$cmversion" = "cm101"  ] 
then
  echo "finalizing for CM10.1-based p4wifi"
  finalizeversion=cm101p
else
  echo "finalizing for phone"
  finalizeversion=$cmversion
fi

#****************************************************************
## Move the ROM to the final ROM preparation stage:
mv $finalout/$romname* ~/android/scripts/finalize_rom_$finalizeversion

#****************************************************************
## Set name of final file:
zipname=`echo $romname`-`echo $romversion`-`echo $cmversion`

#****************************************************************
## Execute the final ROM preparation:
cd ~/android/scripts/finalize_rom_$finalizeversion
rm *.md5sum
echo "Extracting Mackay ROM"
unzip -q $romname* -d MackayExtract

if [ "$trgt" = "galaxysmtd"  ]
then
echo "Copying the updater-script for galaxysmtd"
cp updater-script_s updater-script
fi

if [ "$trgt" = "i9100"  ]
then
echo "Copying the updater-script for i9100"
cp updater-script_s2 updater-script
fi

if [ "$trgt" = "p970"  ]
then
echo "Copying the updater-script for p970"
cp updater-script_p970 updater-script
fi

if [ "$trgt" = "p4wifi"  ]
then
echo "Copying the updater-script for p4wifi"
cp updater-script_p4wifi updater-script
rm MackayExtract/system/app/Apollo.apk
fi

cp updater-script MackayExtract/META-INF/com/google/android
rm updater-script

echo "Copying Gapps"
cp -R gapps/system/* MackayExtract/system
echo "Selecting the correct updater-script"

echo "Repacking Mackay ROM"
cd MackayExtract
zip -qr ../`echo $zipname`.zip ./
cd ..
echo "Signing package..."
java -jar $androidtop/out/host/linux-x86/framework/signapk.jar $secsign/testkey.x509.pem $secsign/testkey.pk8 `echo $zipname`.zip `echo $zipname`-signed.zip

echo "Copying fininalized build to AndroidFlash directory"
cp `echo $zipname`-signed.zip ~/AndroidFlash/$trgt

echo "Cleaning environment"
rm -r MackayExtract
rm $romname*
cd $androidtop
