#!/bin/bash
#

#****************************************************************
## Set basic parameters:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4

#****************************************************************
## Check whether build finished succesfully:
echo "Check whether build of recovery image finished succesfully"
if [ -e $finalout/recovery.img ]
then
  echo "Build finished succesfully"
else
  echo "Build not found, probably a compile error occured"
  exit 0
fi

#****************************************************************
## Set name of the zip:
name=recovery-$trgt

#****************************************************************
## Create & sign the zip:
cd $finalout

rm -rf recovery_zip
mkdir -p recovery_zip/recovery
mkdir -p recovery_zip/META-INF/com/google/android

echo "Copying recovery.img ..."
cp recovery.img recovery_zip/recovery
echo "Copying update-binary ..."
cp system/bin/updater recovery_zip/META-INF/com/google/android/update-binary

echo "Copying updater-script ..."
cat ~/android/scripts/finalize_recovery_p4wifi/recovery_updater-script > recovery_zip/META-INF/com/google/android/updater-script
               
echo "Zipping package..."
cd recovery_zip
zip -qr ../$name.zip ./
cd $finalout

echo "Signing package..."
java -jar $androidtop/out/host/linux-x86/framework/signapk.jar $secsign/testkey.x509.pem $secsign/testkey.pk8 $name.zip $name-signed.zip
rm $name.zip
echo -e "${txtgrn}Package complete:${txtrst} $finalout/$name-signed.zip"
md5sum $name-signed.zip

#****************************************************************
## Copy zip to final location:
echo "Copying fininalized recovery-zip to AndroidFinal directory"
mv $finalout/$name-signed.zip ~/AndroidFlash/p4wifi
cd $androidtop
