#!/bin/bash
#

#****************************************************************
## Set basic parameters:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4
name=$5
version=$6
colour=$7
cmversion=$8

#****************************************************************
## Check whether build finished succesfully:
echo "Check whether $cmversion-based build finished succesfully"
if [ -e $finalout/boot.img ]
then
  echo "Build finished succesfully"
else
  echo "Build not found, probably a compile error occured"
  exit 0
fi

#****************************************************************
## Determine name of the zip:
if [ "$colour" = "cmc" ]
then
name=`echo $name`_`echo $version`_CMC
fi

if [ "$colour" = "voodoo" ]
then
name=`echo $name`_`echo $version`_VC
fi

#****************************************************************
## Create & sign the zip:
cd $finalout

rm -rf kernel_zip
mkdir -p kernel_zip/system/app
mkdir -p kernel_zip/system/etc/init.d
mkdir -p kernel_zip/system/lib/modules
mkdir -p kernel_zip/META-INF/com/google/android

echo "Copying boot.img ..."
cp boot.img kernel_zip/
echo "Copying kernel modules ..."
cp -R system/lib/modules/* kernel_zip/system/lib/modules
echo "Copying update-binary ..."
cp system/bin/updater kernel_zip/META-INF/com/google/android/update-binary

echo "Copying flash & lights.aries.so ..."
cp -R ~/android/scripts/finalize_kernel_s_$cmversion/flash/* kernel_zip/
echo "Copying stock updater-script ..."
cat ~/android/scripts/finalize_kernel_s_$cmversion/kernel_updater-script > kernel_zip/META-INF/com/google/android/updater-script
                
echo "Zipping package..."
cd kernel_zip
zip -qr ../$name.zip ./
cd $finalout

echo "Signing package..."
java -jar $androidtop/out/host/linux-x86/framework/signapk.jar $secsign/testkey.x509.pem $secsign/testkey.pk8 $name.zip $name-signed.zip
rm $name.zip
echo -e "${txtgrn}Package complete:${txtrst} $finalout/$name-signed.zip"
md5sum $name-signed.zip

#****************************************************************
## Copy zip to final location:
echo "Copying fininalized kernel-zip to AndroidFinal directory"
mv $finalout/$name-signed.zip ~/AndroidFlash/$trgt/kernel
cd $androidtop
