#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Check for missing parameters:

if [ "$1" != "p4"  ] && [ "$1" != "p4t"  ] && [ "$1" != "p4v"  ] && [ "$1" != "p4w"  ]
then
  echo "No target device defined"
  exit 0
fi

#****************************************************************
## Set target:

if [ "$1" = "p4" ]
then
trgt=p4
fi

if [ "$1" = "p4t" ]
then
trgt=p4tmo
fi

if [ "$1" = "p4v" ]
then
trgt=p4vzw
fi

if [ "$1" = "p4w" ]
then
trgt=p4wifi
fi

#****************************************************************
## Set folder parameters:
echo "Setting folders"
finalout=~/android/cm102/out/target/product/$trgt
androidtop=~/android/cm102
secsign=~/android/cm102/build/target/product/security

#****************************************************************
## Clean environment:
cd $androidtop/
make installclean
rm $finalout/boot.img

#****************************************************************
## Make the build:
cd $androidtop/
. build/envsetup.sh
breakfast $trgt
mka bootimage

#****************************************************************
## Check whether build finished succesfully:
echo "Check whether p4 kernel build finished succesfully"
if [ -e $finalout/boot.img ]
then
  echo "Build finished succesfully"
else
  echo "Build not found, probably a compile error occured"
  exit 0
fi

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
