#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set basic parameters:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4
romname=$5
romversion=$6
kernelname=$7
kernelversion=$8
cmversion=$9

#****************************************************************
## Clean environment:
cd $androidtop
make installclean
rm $finalout/system/build.prop
rm $finalout/obj/PACKAGING/target_files_intermediates/cm_$trgt-target_files-eng.kasper.zip
rm $finalout/obj/PACKAGING/target_files_intermediates/cm_$trgt-target_files-eng.kasper/SYSTEM/build.prop

#****************************************************************
## Checkout correct recovery:
if [ "$cmversion" = "cm10" ]
then
  cd $androidtop/bootable/recovery
  git checkout mackay
fi
if [ "$cmversion" = "cm101" ]
then
  cd $androidtop/bootable/recovery
  git checkout mackay-cm101
fi

#****************************************************************
## Set kernel version in init:
cd $androidtop/kernel/samsung/aries
git checkout nnt
sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`")\"" $androidtop/kernel/samsung/aries/init/version.c > $androidtop/kernel/samsung/aries/init/version.vc
mv $androidtop/kernel/samsung/aries/init/version.vc $androidtop/kernel/samsung/aries/init/version.c
git add init/version.c
git commit -m "Bump kernel version to `echo $kernelversion`"

#****************************************************************
## Set ROM version in common.mk:
cd $androidtop/vendor/cm
sed "/Mackay/c\    CM_VERSION := `echo $romname`_`echo $romversion`" $androidtop/vendor/cm/config/common.mk > $androidtop/vendor/cm/config/common.updated
mv $androidtop/vendor/cm/config/common.updated $androidtop/vendor/cm/config/common.mk
git add config/common.mk
git commit -m "Bump ROM version to `echo $romversion`"

#****************************************************************
## Make the build:
cd $androidtop
. build/envsetup.sh && brunch $trgt

#****************************************************************
## Finish off the ROM by packing in gapps & updated script:
build_rom_finalize "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${romname}" "${romversion}" "${cmversion}"

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
