#!/bin/bash
#

#****************************************************************
## Set basic parameters:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4
romname=$5
romversion=$6
cmversion=$7

#****************************************************************
## Check whether build finished succesfully:
echo "Check whether $cmversion-based build finished succesfully"
if [ -e $finalout/`echo $romname`_`echo $romversion`.zip ]
then
  echo "Build finished succesfully"
else
  echo "Build not found, probably a compile error occured"
  exit 0
fi

#****************************************************************
## Choose correct finalizing folder:
if [ "$trgt" = "p4wifi"  ] && [ "$cmversion" = "cm101"  ] 
then
  echo "finalizing for CM10.1-based p4wifi"
  finalizeversion=cm101p
else
  echo "finalizing for phone"
  finalizeversion=$cmversion
fi

#****************************************************************
## Move the ROM to the final ROM preparation stage:
mv $finalout/$romname* ~/android/scripts/finalize_rom_$finalizeversion

#****************************************************************
## Set name of final file:
zipname=`echo $romname`-`echo $romversion`-`echo $cmversion`

#****************************************************************
## Execute the final ROM preparation:
cd ~/android/scripts/finalize_rom_$finalizeversion
rm *.md5sum
echo "Extracting Mackay ROM"
unzip -q $romname* -d MackayExtract

if [ "$cmversion" = "cm101" ]
then
  if [ "$trgt" = "galaxysmtd"  ]
  then
    cp updater-script_clean_$trgt updater-script
    cp updater-script MackayExtract/META-INF/com/google/android
    rm updater-script
    rm MackayExtract/system/app/LatinIME.apk
    rm MackayExtract/system/lib/libjni_latinime.so
    echo "Repacking a clean Mackay ROM"
    cd MackayExtract
    zip -qr ../`echo $zipname`-clean.zip ./
    cd ..
    echo "Copying fininalized clean build to AndroidFlash directory"
    mv `echo $zipname`-clean.zip ~/AndroidFlash/$trgt
  fi
fi

echo "Copying the updater-script for $trgt"
cp updater-script_$trgt updater-script

cp updater-script MackayExtract/META-INF/com/google/android
rm updater-script

echo "Removing Apollo & QuickSearchBox"
rm MackayExtract/system/app/Apollo.apk
rm MackayExtract/system/app/QuickSearchBox.apk

echo "Copying Gapps"
cp -R gapps/system/* MackayExtract/system

if [ "$cmversion" = "cm10" ]
then
  echo "Removing VideoEditor for $trgt"
  rm MackayExtract/system/app/VideoEditor.apk
  rm -rf MackayExtract/system/media/video
fi

if [ "$cmversion" = "cm101" ]
then
  if [ "$trgt" = "ace"  ]
  then
    echo "Removing LatinImeGoogle & VideoEditor for $trgt"
    rm MackayExtract/system/app/LatinImeGoogle.apk
    rm MackayExtract/system/lib/libjni_latinimegoogle.so
    rm MackayExtract/system/app/VideoEditor.apk
    rm -rf MackayExtract/system/media/video
  elif [ "$trgt" = "p4wifi"  ] || [ "$trgt" = "galaxysmtd"  ]
  then
    echo "Removing VideoEditor for $trgt"
    rm MackayExtract/system/app/VideoEditor.apk
    rm -rf MackayExtract/system/media/video
  else
    echo "Removing LatinIME & VideoEditor for $trgt"
    rm MackayExtract/system/app/LatinIME.apk
    rm MackayExtract/system/lib/libjni_latinime.so
    rm MackayExtract/system/app/VideoEditor.apk
    rm -rf MackayExtract/system/media/video
  fi
fi

echo "Repacking Mackay ROM"
cd MackayExtract
zip -qr ../`echo $zipname`-full.zip ./
cd ..

echo "Copying fininalized build to AndroidFlash directory"
mv `echo $zipname`-full.zip ~/AndroidFlash/$trgt

echo "Cleaning environment"
rm -r MackayExtract
rm $romname*
cd $androidtop
