#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set basic parameters here:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4
romname=$5
romversion=$6
kernelname=$7
kernelversion=$8

#****************************************************************
## Checkout correct kernel:
if [ "$trgt" = "galaxysmtd"  ]
then
  echo "cleaning recovery"
  recoverycleaning
  echo "cleaning kernel"
  kernelcleaning s c2
  echo "settings kernel version"
  cd $androidtop/kernel/samsung/aries
  sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`")\"" $androidtop/kernel/samsung/aries/init/version.c > $androidtop/kernel/samsung/aries/init/version.vc
  mv $androidtop/kernel/samsung/aries/init/version.vc $androidtop/kernel/samsung/aries/init/version.c
  git add init/version.c
  git commit -m "Bump kernel version to `echo $kernelversion`"
fi

#****************************************************************
## Checkout correct WLAN driver source:
if [ "$trgt" = "p970"  ]
then
  echo "Setting CM10.1 WLAN driver for p970 to enable CM10.2 building"
  cd ~/android/cm102/hardware/broadcom/wlan
  git checkout p970
fi

#****************************************************************
## Clean environment:
cd $androidtop
make installclean
rm $finalout/system/build.prop
rm $finalout/obj/PACKAGING/target_files_intermediates/cm_$trgt-target_files-eng.kasper.zip
rm $finalout/obj/PACKAGING/target_files_intermediates/cm_$trgt-target_files-eng.kasper/SYSTEM/build.prop

#****************************************************************
## Set ROM version in common.mk:
cd $androidtop/vendor/cm
sed "/Mackay/c\    CM_VERSION := `echo $romname`_`echo $romversion`" $androidtop/vendor/cm/config/common.mk > $androidtop/vendor/cm/config/common.updated
mv $androidtop/vendor/cm/config/common.updated $androidtop/vendor/cm/config/common.mk

#****************************************************************
## Make the build:
cd $androidtop/
. build/envsetup.sh && brunch $trgt

cd $androidtop/vendor/cm
git reset --hard
if [ "$trgt" = "p970"  ]
then
  echo "Setting CM10.1 WLAN driver for p970 to enable CM10.2 building"
  cd ~/android/cm102/hardware/broadcom/wlan
  git checkout mackay-cm102
fi
cd $androidtop

#****************************************************************
## Check whether build finished succesfully:
echo "Check whether the build finished succesfully"
if [ -e $finalout/cm-`echo $romname`_`echo $romversion`.zip ]
then
  echo "Build finished succesfully"
else
  echo "Build not found, probably a compile error occured"
  exit 0
fi

echo "Copying fininalized build to AndroidFlash directory"
mv $finalout/cm-`echo $romname`_`echo $romversion`.zip ~/AndroidFlash/$trgt

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
