#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set version info:
rn=Mackay_ROM
rv=1.4.4
kn=Mackay_kernel
kv=0.93
s2rv=$rv-s2
p970rv=$rv-p970
p4wifirv=$rv-p4wifi

#****************************************************************
## Check for missing parameters:

if [ "$1" != "s"  ] && [ "$1" != "s2"  ] && [ "$1" != "p970"  ] && [ "$1" != "p4wifi"  ]
then
  echo "No target device defined"
  exit 0
fi

if [ "$2" != "r"  ] && [ "$2" != "k"  ] && [ "$2" != "4k"  ]
then
  echo "No build specification defined"
  exit 0
fi

#****************************************************************
## Set basic parameters:

if [ "$1" = "s" ]
then
trgt=galaxysmtd
fi

if [ "$1" = "s2" ]
then
trgt=i9100
fi

if [ "$1" = "p970" ]
then
trgt=p970
fi

if [ "$1" = "p4wifi" ]
then
trgt=p4wifi
fi

finalout=~/android/system/out/target/product/$trgt
androidtop=~/android/system
secsign=~/android/system/build/target/product/security

if [ "$trgt" = "galaxysmtd" ]  &&  [ "$2" = "r" ]
then
echo "A rom will be build for $target"
s-cm10 "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${rn}" "${rv}" "${kn}" "${kv}"
fi

if [ "$trgt" = "galaxysmtd" ]  &&  [ "$2" = "k" ]
then
echo "A stock kernel will be build for $target"
s-kernel "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${kn}" "${kv}"
fi

if [ "$trgt" = "galaxysmtd" ]  &&  [ "$2" = "4k" ]
then
echo "All four kernel flavours will be build for $target"
s-4kernels "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${kn}" "${kv}"
fi

if [ "$trgt" = "i9100"  ]  &&  [ "$2" = "r" ]
then
echo "A rom will be build for $target"
s2-cm10 "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${rn}" "${s2rv}"
fi

if [ "$trgt" = "p970"  ]  &&  [ "$2" = "r" ]
then
echo "A rom will be build for $target"
p970-cm10 "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${rn}" "${p970rv}"
fi

if [ "$trgt" = "p4wifi"  ]  &&  [ "$2" = "r" ]
then
echo "A rom will be build for $target"
p4wifi-cm10 "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${rn}" "${p4wifirv}"
fi
