#!/bin/bash
#

#****************************************************************
## Set basic parameters:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4
name=$5
version=$6
cmversion=$7

#****************************************************************
## Clean build environment:
cd $androidtop
rm $finalout/boot.img

#****************************************************************
## Check whether prerequisites need to be build:
if [ ! -e $androidtop/out/host/linux-x86/framework/signapk.jar ]
then
  echo "Signapk.jar not found, rebuilding..."
  mka signapk
fi

if [ ! -e $finalout/system/bin/updater ]
then
  echo "Updater binary not found, rebuilding..."
  mka updater
fi

#*************************STOCK/VOODOO***************************
echo "Buil kernel 2 - stock led & voodoo colour"
sed "/CONFIG_FB_VOODOO=n/c\CONFIG_FB_VOODOO=y" $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig > $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vc
mv $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vc $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig

sed "/Mackay/c\	\" ("`echo $name`_`echo $version`_VC")\"" $androidtop/kernel/samsung/aries/init/version.c > $androidtop/kernel/samsung/aries/init/version.vc
mv $androidtop/kernel/samsung/aries/init/version.vc $androidtop/kernel/samsung/aries/init/version.c

cd $androidtop/
. build/envsetup.sh
breakfast galaxysmtd
mka bootimage

light=stock
colour=voodoo
build_kernel_s_finalize "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${name}" "${version}" "${light}" "${colour}" "${cmversion}"

#****************************************************************
## Clean build environment:
rm $finalout/boot.img

#**************************BLN/VOODOO****************************
echo "Buil kernel 3 - BLN & voodoo colour"
sed "/CONFIG_GENERIC_BLN=n/c\CONFIG_GENERIC_BLN=y" $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig > $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vcbln
mv $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vcbln $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig

sed "/Mackay/c\	\" ("`echo $name`_`echo $version`_VC_BLN")\"" $androidtop/kernel/samsung/aries/init/version.c > $androidtop/kernel/samsung/aries/init/version.vcbln
mv $androidtop/kernel/samsung/aries/init/version.vcbln $androidtop/kernel/samsung/aries/init/version.c

cd $androidtop/
. build/envsetup.sh
breakfast galaxysmtd
mka bootimage

light=bln
colour=voodoo
build_kernel_s_finalize "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${name}" "${version}" "${light}" "${colour}" "${cmversion}"

#**************************BLN/STOCK*****************************
echo "Buil kernel 4 - BLN & stock colour"
sed "/CONFIG_FB_VOODOO=y/c\CONFIG_FB_VOODOO=n" $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig > $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.bln
mv $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.bln $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig

sed "/Mackay/c\	\" ("`echo $name`_`echo $version`_BLN")\"" $androidtop/kernel/samsung/aries/init/version.c > $androidtop/kernel/samsung/aries/init/version.bln
mv $androidtop/kernel/samsung/aries/init/version.bln $androidtop/kernel/samsung/aries/init/version.c

cd $androidtop/
. build/envsetup.sh
breakfast galaxysmtd
mka bootimage

light=bln
colour=cmc
build_kernel_s_finalize "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${name}" "${version}" "${light}" "${colour}" "${cmversion}"

#****************************************************************
## Clean build environment:
rm $finalout/boot.img

#*********************Restore Stock Value************************
echo "Set back to stock values"
cd $androidtop/kernel/samsung/aries/
git reset --hard
cd $androidtop
