#!/bin/bash
#

#****************************************************************
## Set basic parameters:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4
name=$5
version=$6
cmversion=$7

#****************************************************************
## Clean build environment:
cd $androidtop
make installclean
rm $finalout/boot.img

#****************************************************************
## Set kernel version in init:
cd $androidtop/kernel/samsung/p4
sed "/Mackay/c\	\" ("`echo $name`_`echo $version`")\"" $androidtop/kernel/samsung/p4/init/version.c > $androidtop/kernel/samsung/p4/init/version.vc
mv $androidtop/kernel/samsung/p4/init/version.vc $androidtop/kernel/samsung/p4/init/version.c
git add $androidtop/kernel/samsung/p4/init/version.c
git commit -m "Bump kernel version to `echo $version`"

#****************************************************************
## Build the kernel:
cd $androidtop/
. build/envsetup.sh
breakfast $trgt
mka bootimage

#****************************************************************
## Check whether other prerequisites need to be build:
if [ ! -e $androidtop/out/host/linux-x86/framework/signapk.jar ]
then
  echo "Signapk.jar not found, rebuilding..."
  mka signapk
fi

if [ ! -e $finalout/system/bin/updater ]
then
  echo "Updater binary not found, rebuilding..."
  mka updater
fi

#****************************************************************
## Finish off the kernel by packing it in a zip:
build_kernel_p_finalize "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${name}" "${version}"
