#!/bin/bash
#

#****************************************************************
## Set basic parameters:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4
name=$5
version=$6
cmversion=$7

#****************************************************************
## Clean build environment:
cd $androidtop
make installclean
rm $finalout/boot.img

#****************************************************************
## Set kernel version in init:
cd $androidtop/kernel/samsung/aries
sed "/Mackay/c\	\" ("`echo $name`_`echo $version`")\"" $androidtop/kernel/samsung/aries/init/version.c > $androidtop/kernel/samsung/aries/init/version.vc
mv $androidtop/kernel/samsung/aries/init/version.vc $androidtop/kernel/samsung/aries/init/version.c
git add $androidtop/kernel/samsung/aries/init/version.c
git commit -m "Bump kernel version to `echo $version`"

#**************************STOCK*********************************
echo "Buil kernel 1 - stock colour"
cd $androidtop/
. build/envsetup.sh
breakfast galaxysmtd
mka bootimage

#****************************************************************
## Check whether other prerequisites need to be build:
if [ ! -e $androidtop/out/host/linux-x86/framework/signapk.jar ]
then
  echo "Signapk.jar not found, rebuilding..."
  mka signapk
fi

if [ ! -e $finalout/system/bin/updater ]
then
  echo "Updater binary not found, rebuilding..."
  mka updater
fi

#****************************************************************
## Finish off the kernel by packing it in a zip:
colour=cmc
build_kernel_s_finalize "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${name}" "${version}" "${colour}" "${cmversion}"

#****************************************************************
## Clean build environment:
rm $finalout/boot.img

#*************************VOODOO*********************************
echo "Buil kernel 2 - voodoo colour"
sed "/CONFIG_FB_VOODOO=n/c\CONFIG_FB_VOODOO=y" $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig > $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vc
mv $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vc $androidtop/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig

sed "/Mackay/c\	\" ("`echo $name`_`echo $version`_VC")\"" $androidtop/kernel/samsung/aries/init/version.c > $androidtop/kernel/samsung/aries/init/version.vc
mv $androidtop/kernel/samsung/aries/init/version.vc $androidtop/kernel/samsung/aries/init/version.c

cd $androidtop/
. build/envsetup.sh
breakfast galaxysmtd
mka bootimage

colour=voodoo
build_kernel_s_finalize "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${name}" "${version}" "${colour}" "${cmversion}"

#*********************Restore Stock Value************************
echo "Set back to stock values"
cd $androidtop/kernel/samsung/aries/
git reset --hard
cd $androidtop
