#!/bin/bash
#

# Keep stock CM10.1 kernel up-to-date
cd ~/android/carbon/bionic
git checkout stock
cd ~/android/carbon/dalvik
git checkout stock

# Sync CM10.1 phone sources
cd ~/android/carbon/
repo sync -j8

# Return to mackay kernel
cd ~/android/carbon/bionic
git checkout infamous-jb3
cd ~/android/carbon/dalvik
git checkout infamous-jb3

