#!/bin/bash
#

#****************************************************************
## Checkout correct recovery:
cd $androidtop/bootable/recovery
git checkout mackay

#****************************************************************
## Checkout stock kernel:
cd $androidtop/kernel/samsung/aries
git checkout stock
cd $androidtop

#****************************************************************
## Do the sync itself:
repo sync -j8

#****************************************************************
## Checkout mackay kernel:
cd $androidtop/kernel/samsung/aries
git checkout mackay
