#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set version info:
rn=Mackay_ROM
rv=1.7.0
kn=Mackay_kernel
kv=0.170
s2rv=$rv-s2
p970rv=$rv-p970
p4wifirv=$rv-p4wifi
cmversion=cm10

#****************************************************************
## Check for missing parameters:

if [ "$1" != "s"  ] && [ "$1" != "p970"  ]
then
  echo "No target device defined"
  exit 0
fi

if [ "$2" != "r"  ] && [ "$2" != "k"  ] && [ "$2" != "4k"  ]
then
  echo "No build specification defined"
  exit 0
fi

#****************************************************************
## Set target:

if [ "$1" = "s" ]
then
trgt=galaxysmtd
fi

if [ "$1" = "p970" ]
then
trgt=p970
fi

#****************************************************************
## Set basic folder parameters:
finalout=~/android/cm10/out/target/product/$trgt
androidtop=~/android/cm10
secsign=~/android/cm10/build/target/product/security

#****************************************************************
## Start the build:
if [ "$trgt" = "galaxysmtd" ]  &&  [ "$2" = "r" ]
then
echo "A rom will be build for $trgt"
build_rom_s "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${rn}" "${rv}" "${kn}" "${kv}" "${cmversion}"
fi

if [ "$trgt" = "galaxysmtd" ]  &&  [ "$2" = "k" ]
then
echo "A stock kernel will be build for $trgt"
build_kernel_s "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${kn}" "${kv}" "${cmversion}"
fi

if [ "$trgt" = "galaxysmtd" ]  &&  [ "$2" = "4k" ]
then
echo "All four kernel flavours will be build for $trgt"
build_kernel_s_4 "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${kn}" "${kv}" "${cmversion}"
fi

if [ "$trgt" = "p970"  ]  &&  [ "$2" = "r" ]
then
echo "A rom will be build for $trgt"
build_rom "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${rn}" "${p970rv}" "${cmversion}"
fi
