#!/bin/bash

trgt=$1
finalout=$2
androidtop=$3
secsign=$4
name=$5
version=$6

#****************************************************************
## Check whether build finished succesfully:
echo "Check whether build of CM10.1-based kernel finished succesfully"
if [ -e $finalout/boot.img ]
then
  echo "Build finished succesfully"
else
  echo "Build not found, probably a compile error occured"
  exit 0
fi

#****************************************************************
## Set name of the zip:
name=`echo $name`_`echo $version`

#****************************************************************
## Create & sign the zip:
cd $finalout

rm -rf kernel_zip
mkdir -p kernel_zip/system/lib/modules
mkdir -p kernel_zip/META-INF/com/google/android

echo "Copying boot.img ..."
cp boot.img kernel_zip/
echo "Copying kernel modules ..."
cp -R system/lib/modules/* kernel_zip/system/lib/modules
echo "Copying update-binary ..."
cp system/bin/updater kernel_zip/META-INF/com/google/android/update-binary

echo "Copying updater-script ..."
cat ~/android/scripts/finalize_p4wifi_kernel_101/kernel_updater-script > kernel_zip/META-INF/com/google/android/updater-script
               
echo "Zipping package..."
cd kernel_zip
zip -qr ../$name.zip ./
cd $finalout

echo "Signing package..."
java -jar $androidtop/out/host/linux-x86/framework/signapk.jar $secsign/testkey.x509.pem $secsign/testkey.pk8 $name.zip $name-signed.zip
rm $name.zip
echo -e "${txtgrn}Package complete:${txtrst} $finalout/$name-signed.zip"
md5sum $name-signed.zip

#****************************************************************
## Copy zip to final location:
echo "Copying fininalized kernel-zip to AndroidFinal directory"
mv $finalout/$name-signed.zip ~/AndroidFlash/p4wifi
cd ~/android/cm101tab
