#!/bin/bash
#

# Keep stock CM10.1 kernel up-to-date
cd ~/android/cm101/kernel/samsung/aries
git checkout stock
cd ~/android/cm101/bootable/recovery
git checkout stock
cd ~/android/cm101/device/samsung/aries-common
git checkout mackay-cm101

# Sync CM10.1 phone sources
cd ~/android/cm101/
repo sync -j8

# Return to mackay kernel
cd ~/android/cm101/kernel/samsung/aries
git checkout mackay-cm101

# Return to rootbox
cd ~/android/carbondev/packages/apps/Camera
git checkout rootbox
cd ~/android/carbondev/packages/apps/Gallery2
git checkout rootbox
