#!/bin/bash
#

#****************************************************************
## Set basic parameters:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4
romname=$5
romversion=$6

#****************************************************************
## Check whether build finished succesfully:
echo "Check whether CM10.1-based build finished succesfully"
if [ -e $finalout/`echo $romname`_`echo $romversion`.zip ]
then
  echo "Build finished succesfully"
else
  echo "Build not found, probably a compile error occured"
  exit 0
fi

#****************************************************************
## Move the ROM to the final ROM preparation stage:
mv $finalout/$romname* ~/android/scripts/finalize_p4wifi_101

#****************************************************************
## Execute the final ROM preparation:
cd ~/android/scripts/finalize_p4wifi_101
rm *.md5sum

echo "Extracting Mackay ROM"
unzip -q $romname* -d MackayExtract

echo "Copying Gapps"
cp -R gapps/system/* MackayExtract/system
rm MackayExtract/system/app/Gallery2.apk

echo "Copy the updater-script"
cp updater-script MackayExtract/META-INF/com/google/android
rm updater-script

echo "Repacking Mackay ROM"
cd MackayExtract
zip -qr ../`echo $romname`-`echo $romversion`.zip ./
cd ..

echo "Signing package..."
java -jar $androidtop/out/host/linux-x86/framework/signapk.jar $secsign/testkey.x509.pem $secsign/testkey.pk8 `echo $romname`-`echo $romversion`.zip `echo $romname`-`echo $romversion`-signed.zip

echo "Copying fininalized build to AndroidFlash directory"
cp `echo $romname`-`echo $romversion`-signed.zip ~/AndroidFlash/p4wifi

echo "Cleaning environment"
rm -r MackayExtract
rm $romname*
cd ~/android/cm101tab
