#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set version info:
rn=Mackay_ROM
rv=2.10.6
kn=Mackay_kernel
kv=0.313
kvb=$kv-sb
s2rv=$rv-s2
p970rv=$rv-p970

#****************************************************************
## Check for missing parameters:

if [ "$1" != "s"  ] && [ "$1" != "sb"  ] && [ "$1" != "s2"  ] && [ "$1" != "p970"  ] && [ "$1" != "ace"  ]
then
  echo "No target device defined"
  exit 0
fi

if [ "$2" != "r"  ] && [ "$2" != "k"  ] && [ "$2" != "kv"  ] && [ "$2" != "2k"  ]
then
  echo "No build specification defined"
  exit 0
fi

#****************************************************************
## Set target:

if [ "$1" = "s" ]
then
trgt=galaxysmtd
fi

if [ "$1" = "sb" ]
then
trgt=galaxysbmtd
fi
if [ "$1" = "s2" ]
then
trgt=i9100
fi

if [ "$1" = "p970" ]
then
trgt=p970
fi


#****************************************************************
## Set basic phone folder parameters:
if [ "$1" = "s"  ] || [ "$1" = "sb"  ] || [ "$1" = "s2"  ] || [ "$1" = "p970"  ]
then
echo "Setting phone folders"
finalout=~/android/cm101/out/target/product/$trgt
androidtop=~/android/cm101
secsign=~/android/cm101/build/target/product/security
fi

#****************************************************************
## Start the build:
if [ "$trgt" = "galaxysmtd" ]  &&  [ "$2" = "r" ]
then
echo "A CM10.1-based rom will be build for $trgt"
build_rom "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${rn}" "${rv}" "${kn}" "${kv}"
fi

if [ "$trgt" = "galaxysmtd" ]  &&  [ "$2" = "k" ]
then
echo "A single CM10.1-based kernel will be build for $trgt"
build_kernel_s "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${kn}" "${kv}"
fi

if [ "$trgt" = "galaxysmtd" ]  &&  [ "$2" = "kv" ]
then
echo "A single voodoo CM10.1-based kernel will be build for $trgt"
build_kernel_sv "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${kn}" "${kv}"
fi

if [ "$trgt" = "galaxysmtd" ]  &&  [ "$2" = "2k" ]
then
echo "Both CM10.1-based kernel flavours will be build for $trgt"
build_kernel_s_2 "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${kn}" "${kv}"
fi

if [ "$trgt" = "i9100"  ]  &&  [ "$2" = "r" ]
then
echo "A CM10.1-based rom will be build for $trgt"
build_rom "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${rn}" "${s2rv}" "${kn}" "${kv}"
fi

if [ "$trgt" = "p970"  ]  &&  [ "$2" = "r" ]
then
echo "A CM10.1-based rom will be build for $trgt"
build_rom "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${rn}" "${p970rv}" "${kn}" "${kv}"
fi

if [ "$trgt" = "p970"  ]  &&  [ "$2" = "k" ]
then
echo "A CM10.1-based kernel will be build for $trgt"
build_kernel_p970 "${trgt}" "${finalout}" "${androidtop}" "${secsign}"
fi
