#!/bin/bash
#

# Keep stock CM10.1 kernel up-to-date
cd ~/android/cm101/kernel/samsung/aries
git checkout stock

# Sync CM10.1 phone sources
cd ~/android/cm101/
repo sync -j8

# Return to mackay kernel
cd ~/android/cm101/kernel/samsung/aries
git checkout mackay-cm101
