#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set version info:
rn=Mackay_ROM
rv=2.3.1
kn=Mackay_kernel
kv=0.230
s2rv=$rv-s2
p970rv=$rv-p970
p4wifirv=$rv-p4wifi
sbkv=$kv-sb
cmversion=cm101

#****************************************************************
## Check for missing parameters:

if [ "$1" != "s"  ] && [ "$1" != "sb"  ] && [ "$1" != "s2"  ] && [ "$1" != "p970"  ] && [ "$1" != "p4wifi"  ]
then
  echo "No target device defined"
  exit 0
fi

if [ "$2" != "r"  ] && [ "$2" != "k"  ] && [ "$2" != "4k"  ]
then
  echo "No build specification defined"
  exit 0
fi

#****************************************************************
## Set target:

if [ "$1" = "s" ]
then
trgt=galaxysmtd
fi

if [ "$1" = "sb" ]
then
trgt=galaxysbmtd
fi

if [ "$1" = "s2" ]
then
trgt=i9100
fi

if [ "$1" = "p970" ]
then
trgt=p970
fi

if [ "$1" = "p4wifi" ]
then
trgt=p4wifi
fi

#****************************************************************
## Set basic phone folder parameters:
if [ "$1" = "s"  ] || [ "$1" = "sb"  ] || [ "$1" = "s2"  ] || [ "$1" = "p970"  ]
then
echo "Setting phone folders"
finalout=~/android/cm101/out/target/product/$trgt
androidtop=~/android/cm101
secsign=~/android/cm101/build/target/product/security
fi

#****************************************************************
## Set basic tablet folder parameters:
if [ "$1" = "p4wifi" ] && [ "$2" != "rec"  ]
then
echo "Setting tablet folders"
finalout=~/android/cm101tab/out/target/product/$trgt
androidtop=~/android/cm101tab
secsign=~/android/cm101tab/build/target/product/security
fi

#****************************************************************
## Start the build:
if [ "$trgt" = "galaxysmtd" ]  &&  [ "$2" = "r" ]
then
echo "A CM10.1-based rom will be build for $trgt"
build_rom_s "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${rn}" "${rv}" "${kn}" "${kv}" "${cmversion}"
fi

if [ "$trgt" = "galaxysmtd" ]  &&  [ "$2" = "k" ]
then
echo "A single CM10.1-based kernel will be build for $trgt"
build_kernel_s "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${kn}" "${kv}" "${cmversion}"
fi

if [ "$trgt" = "galaxysmtd" ]  &&  [ "$2" = "4k" ]
then
echo "All four CM10.1-based kernel flavours will be build for $trgt"
build_kernel_s_4 "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${kn}" "${kv}" "${cmversion}"
fi

if [ "$trgt" = "galaxysbmtd" ]  &&  [ "$2" = "4k" ]
then
echo "All four CM10.1-based kernel flavours will be build for $trgt"
build_kernel_sb_4 "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${kn}" "${sbkv}" "${cmversion}"
fi

if [ "$trgt" = "i9100"  ]  &&  [ "$2" = "r" ]
then
echo "A CM10.1-based rom will be build for $trgt"
build_rom "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${rn}" "${s2rv}" "${cmversion}"
fi

if [ "$trgt" = "p970"  ]  &&  [ "$2" = "r" ]
then
echo "A CM10.1-based rom will be build for $trgt"
build_rom "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${rn}" "${p970rv}" "${cmversion}"
fi

if [ "$trgt" = "p4wifi"  ]  &&  [ "$2" = "r" ]
then
echo "A CM10.1-based rom will be build for $trgt"
build_rom_p "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${rn}" "${p4wifirv}" "${kn}" "${kv}" "${cmversion}"
fi

if [ "$trgt" = "p4wifi" ]  &&  [ "$2" = "k" ]
then
echo "A CM10.1-based kernel will be build for $trgt"
build_kernel_p "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${kn}" "${kv}" "${cmversion}"
fi
