#!/bin/bash
#

#****************************************************************
## Set basic parameters:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4
romname=$5
romversion=$6

#****************************************************************
## Check whether build finished succesfully:
echo "Check whether build finished succesfully"
if [ -e $finalout/`echo $romname`_`echo $romversion`.zip ]
then
  echo "Build finished succesfully"
else
  echo "Build not found, probably a compile error occured"
  exit 0
fi

#****************************************************************
## Move the ROM to the final ROM preparation stage:
mv $finalout/$romname* ~/android/scripts/finalize_rom

#****************************************************************
## Execute the final ROM preparation:
cd ~/android/scripts/finalize_rom
rm *.md5sum
echo "Extracting Mackay ROM"
unzip -q $romname* -d MackayExtract
echo "Copying Gapps"
cp -R gapps/system/* MackayExtract/system
echo "Selecting the correct updater-script"

if [ "$trgt" = "galaxysmtd"  ]
then
echo "Copying the updater-script for galaxysmtd"
cp updater-script_s updater-script
fi

if [ "$trgt" = "i9100"  ]
then
echo "Copying the updater-script for i9100"
cp updater-script_s2 updater-script
fi

if [ "$trgt" = "p970"  ]
then
echo "Copying the updater-script for p970"
cp updater-script_p970 updater-script
fi

if [ "$trgt" = "p4wifi"  ]
then
echo "Copying the updater-script for p4wifi"
cp updater-script_p4wifi updater-script
fi

cp updater-script MackayExtract/META-INF/com/google/android
rm updater-script
echo "Repacking Mackay ROM"
cd MackayExtract
zip -qr ../`echo $romname`-`echo $romversion`.zip ./
cd ..
echo "Signing package..."
java -jar $androidtop/out/host/linux-x86/framework/signapk.jar $secsign/testkey.x509.pem $secsign/testkey.pk8 `echo $romname`-`echo $romversion`.zip `echo $romname`-`echo $romversion`-signed.zip

if [ "$trgt" = "galaxysmtd"  ]
then
echo "Copying fininalized build to AndroidFlash directory"
cp `echo $romname`-`echo $romversion`-signed.zip ~/AndroidFlash/i9000_rom
fi

if [ "$trgt" = "i9100"  ]
then
echo "Copying fininalized build to AndroidFlash directory"
cp `echo $romname`-`echo $romversion`-signed.zip ~/AndroidFlash/i9100
fi

if [ "$trgt" = "p970"  ]
then
echo "Copying fininalized build to AndroidFlash directory"
cp `echo $romname`-`echo $romversion`-signed.zip ~/AndroidFlash/p970
fi

if [ "$trgt" = "p4wifi"  ]
then
echo "Copying fininalized build to AndroidFlash directory"
cp `echo $romname`-`echo $romversion`-signed.zip ~/AndroidFlash/p4wifi
fi

echo "Cleaning environment"
rm -r MackayExtract
rm $romname*
cd ~/android/cm10
