#!/bin/bash
#

# Sync CM10.1 phone sources
cd ~/android/cm11/
repo sync -j8

# Choose correct branches
cd ~/android/cm11/kernel/samsung/aries
git checkout mackay-cm11
cd ~/android/cm11/bootable/recovery
git checkout twrp-cm11
cd ~/android/cm11/device/samsung/galaxysmtd
git checkout twrp-cm11
cd ~/android/cm11/device/samsung/aries-common
git checkout twrp-cm11
