#!/bin/bash
#

#****************************************************************
## Set basic parameters:
target=$1
out=$2
top=$3
sec=$4
romname=$5
romversion=$6

#****************************************************************
## Check whether build finished succesfully:
echo "Check whether build finished succesfully"
if [ -e $out/`echo $romname`_`echo $romversion`.zip ]
then
  echo "Build finished succesfully"
else
  echo "Build not found, probably a compile error occured"
  exit 0
fi

#****************************************************************
## Move the ROM to the final ROM preparation stage:
mv $out/$romname* finalize_build

#****************************************************************
## Execute the final ROM preparation:
cd ~/android/system/finalize_build
rm *.md5sum
echo "Extracting Mackay ROM"
unzip -q $romname* -d MackayExtract
echo "Copying Gapps"
cp -R gapps/system/* MackayExtract/system
echo "Selecting the correct updater-script"

if [ "$target" = "galaxysmtd"  ]
then
echo "Copying the updater-script for galaxysmtd"
cp updater-script_s updater-script
fi

if [ "$target" = "i9100"  ]
then
echo "Copying the updater-script for i9100"
cp updater-script_s2 updater-script
fi

cp updater-script MackayExtract/META-INF/com/google/android
rm updater-script
echo "Repacking Mackay ROM"
cd MackayExtract
zip -qr ../`echo $romname`-`echo $romversion`.zip ./
cd ..
echo "Signing package..."
java -jar $top/out/host/linux-x86/framework/signapk.jar $sec/testkey.x509.pem $sec/testkey.pk8 `echo $romname`-`echo $romversion`.zip `echo $romname`-`echo $romversion`-signed.zip

if [ "$target" = "galaxysmtd"  ]
then
echo "Copying fininalized build to AndroidFlash & AndroidFinal directory"
cp `echo $romname`-`echo $romversion`-signed.zip ~/AndroidFlash
cp `echo $romname`-`echo $romversion`-signed.zip ~/android/system/finalize_build/AndroidFinished
fi

if [ "$target" = "i9100"  ]
then
echo "Copying fininalized build to AndroidFinal directory"
cp `echo $romname`-`echo $romversion`-signed.zip ~/android/system/finalize_build/AndroidFinished
fi

echo "Cleaning environment"
rm -r MackayExtract
rm $romname*
cd ~/android/system
