#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set version info:
romname=Mackay_ROM
romversion=1.6Unicorn
trgt=galaxysmtd

#****************************************************************
## Set AOKP folder parameters:
echo "Setting aokp folders"
finalout=~/android/aokp/out/target/product/$trgt
androidtop=~/android/aokp
secsign=~/android/aokp/build/target/product/security

#****************************************************************
## Clean environment:
cd $androidtop
make installclean
rm $finalout/system/build.prop
rm $finalout/obj/PACKAGING/target_files_intermediates/aokp_$trgt-target_files-eng.kasper.zip
rm $finalout/obj/PACKAGING/target_files_intermediates/aokp_$trgt-target_files-eng.kasper/SYSTEM/build.prop

#****************************************************************
## Set ROM version:
cd $androidtop/vendor/aokp
sed "/Infamous/c\        ro.aokp.version=`echo $romname`_`echo $romversion`" $androidtop/vendor/aokp/configs/common_versions.mk > $androidtop/vendor/aokp/configs/common_versions.updated
mv $androidtop/vendor/aokp/configs/common_versions.updated $androidtop/vendor/aokp/configs/common_versions.mk
sed "/Mackay/c\        ro.aokp.version=`echo $romname`_`echo $romversion`" $androidtop/vendor/aokp/configs/common_versions.mk > $androidtop/vendor/aokp/configs/common_versions.updated
mv $androidtop/vendor/aokp/configs/common_versions.updated $androidtop/vendor/aokp/configs/common_versions.mk

#****************************************************************
## Make the build:
cd $androidtop/
. build/envsetup.sh && brunch $trgt

#****************************************************************
## Check whether build finished succesfully:
echo "Check whether the build finished succesfully"
if [ -e $finalout/`echo $romname`_`echo $romversion`.zip ]
then
  echo "Build finished succesfully"
else
  echo "Build not found, probably a compile error occured"
  exit 0
fi

#****************************************************************
## Move the ROM to the final ROM preparation stage:
mv $finalout/$romname* ~/android/scripts/finalize_rom

#****************************************************************
## Set name of final file:
zipname=`echo $romname`-`echo $romversion`

#****************************************************************
## Execute the final ROM preparation:
cd ~/android/scripts/finalize_rom
rm *.md5sum
echo "Extracting Mackay ROM"
unzip -q $romname* -d MackayExtract

echo "Copying the updater-script for $trgt"
cp updater-script_galaxysmtd_aokp updater-script
cp updater-script MackayExtract/META-INF/com/google/android
rm updater-script

echo "Copying Gapps"
cp -R gapps/system/* MackayExtract/system

echo "Repacking Mackay ROM"
cd MackayExtract
zip -qr ../`echo $zipname`.zip ./
cd ..

echo "Copying fininalized build to AndroidFlash directory"
mv `echo $zipname`.zip ~/AndroidFlash/$trgt

echo "Cleaning environment"
rm -r MackayExtract
rm $romname*

cd $androidtop/vendor/aokp
git reset --hard
cd $androidtop

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
