#!/bin/bash
#

# Choose correct branches
cd ~/android/omni/kernel/lge/hammerhead
git checkout stock
cd ~/android/omni/device/lge/hammerhead
git checkout stock
cd ~/android/omni/kernel/samsung/aries
git checkout stock
cd ~/android/omni/device/samsung/aries-common
git checkout stock
cd ~/android/omni/device/samsung/galaxysmtd
git checkout stock
cd ~/android/omni/harware/samsung
git checkout stock
cd ~/android/omni/bootable/recovery
git checkout stock

# Sync Omni sources
cd ~/android/omni
repo sync -j8

# Choose correct branches
cd ~/android/omni/kernel/lge/hammerhead
git checkout mackay-omni-mpm
cd ~/android/omni/device/lge/hammerhead
git checkout mackay-omni-mpm
cd ~/android/omni/kernel/samsung/aries
git checkout mackay-omni
cd ~/android/omni/device/samsung/aries-common
git checkout mackay-omni
cd ~/android/omni/device/samsung/galaxysmtd
git checkout mackay-omni
cd ~/android/omni/harware/samsung
git checkout mackay-omni
cd ~/android/omni/bootable/recovery
git checkout mackay-omni
