#!/bin/bash
#

# Choose correct branches
cd ~/android/cm11/kernel/lge/hammerhead
git checkout stock
cd ~/android/cm11/bootable/recovery
git checkout stock

# Sync Omni sources
cd ~/android/omni
repo sync -j8

# Choose correct branches
cd ~/android/cm11/kernel/lge/hammerhead
git checkout mackay-omni
cd ~/android/cm11/bootable/recovery
git checkout mackay-omni
