#!/bin/bash
#

# Choose correct branches
cd ~/android/omni/kernel/lge/hammerhead
git checkout stock
cd ~/android/omni/device/lge/hammerhead
git checkout stock
cd ~/android/omni/bootable/recovery
git checkout stock

# Sync Omni sources
cd ~/android/omni
repo sync -j8

# Choose correct branches
cd ~/android/omni/kernel/lge/hammerhead
git checkout mackay-omni-new
cd ~/android/omni/device/lge/hammerhead
git checkout mackay-omni-new
cd ~/android/omni/bootable/recovery
git checkout mackay-omni
