#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Check for missing parameters:

if [ "$1" != "s"  ] && [ "$1" != "p4w"  ] && [ "$1" != "p4"  ] && [ "$1" != "hh"  ] && [ "$1" != "m7"  ]
then
  echo "No target device defined"
  exit 0
fi

#****************************************************************
## Set target:

if [ "$1" = "s" ]
then
trgt=galaxysmtd
# cd ~/android/omni/frameworks/native
# git checkout mackay-omni
cd ~/android/omni/frameworks/av
git checkout stock
fi

if [ "$1" = "p4w" ]
then
trgt=p4wifi
# cd ~/android/omni/frameworks/native
# git checkout mackay-omni-keep
cd ~/android/omni/frameworks/av
git checkout mackay-omni
fi

if [ "$1" = "p4" ]
then
trgt=p4
# cd ~/android/omni/frameworks/native
# git checkout mackay-omni-keep
cd ~/android/omni/frameworks/av
git checkout mackay-omni
fi

if [ "$1" = "hh" ]
then
trgt=hammerhead
# cd ~/android/omni/frameworks/native
# git checkout mackay-omni
cd ~/android/omni/frameworks/av
git checkout stock
fi

if [ "$1" = "m7" ]
then
trgt=m7ul
# cd ~/android/omni/frameworks/native
# git checkout mackay-omni
cd ~/android/omni/frameworks/av
git checkout stock
fi


#****************************************************************
## Set basic folder parameters:
echo "Setting folders"
finalout=~/android/omni/out/target/product/$trgt
androidtop=~/android/omni
secsign=~/android/omni/build/target/product/security

#****************************************************************
## Start the build:
echo "An OMNI ROM will be build for $trgt"

#****************************************************************
## Clean environment:
cd $androidtop
make installclean
rm $finalout/system/build.prop
rm $finalout/obj/PACKAGING/target_files_intermediates/omni_`echo $trgt`-target_files-eng.kasper.zip
rm $finalout/obj/PACKAGING/target_files_intermediates/omni_`echo $trgt`-target_files-eng.kasper/SYSTEM/build.prop

#****************************************************************
## Make the build:
cd $androidtop/
. build/envsetup.sh
export USE_CCACHE=1
brunch omni_`echo $trgt`-userdebug

#****************************************************************
## Copy the build:
echo "Copying fininalized build to AndroidFlash directory"
mv $finalout/omni-*.zip ~/AndroidFlash/$trgt

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
