#!/bin/bash
#

#****************************************************************
## Check for missing parameters:

if [ "$1" != "s"  ] && [ "$1" != "p4"  ] && [ "$1" != "p4t"  ] && [ "$1" != "p4v"  ] && [ "$1" != "p4w"  ] && [ "$1" != "p970"  ]
then
  echo "No target device defined"
  exit 0
fi

#****************************************************************
## Set target:

if [ "$1" = "s" ]
then
trgt=galaxysmtd
fi

if [ "$1" = "p4" ]
then
trgt=p4
fi

if [ "$1" = "p4t" ]
then
trgt=p4tmo
fi

if [ "$1" = "p4v" ]
then
trgt=p4vzw
fi

if [ "$1" = "p4w" ]
then
trgt=p4wifi
fi

if [ "$1" = "p970" ]
then
trgt=p970
fi

#****************************************************************
## Set basic folder parameters:
echo "Setting folders"
androidtop=~/android/paranoid
finalout=~/android/paranoid/out/target/product/$trgt

#****************************************************************
## Start the build:
echo "An ParanoidAndroid ROM will be build for $trgt"

#****************************************************************
## Clean environment:
cd $androidtop
make installclean
rm $finalout/system/build.prop
rm $finalout/obj/PACKAGING/target_files_intermediates/pa_$trgt-target_files-eng.kasper.zip
rm $finalout/obj/PACKAGING/target_files_intermediates/pa_$trgt-target_files-eng.kasper/SYSTEM/build.prop

#****************************************************************
## Make the build:
cd $androidtop/
./rom-build.sh $trgt

echo "Copying fininalized build to AndroidFlash directory"
mv $finalout/pa_*.zip ~/AndroidFlash/$trgt
