#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set basic parameters:
device=galaxysmtd
out=~/android/system/out/target/product/$device
top=~/android/system
sec=~/android/system/build/target/product/security

romname=Mackay_ROM
romversion=1.3.0-wipe
kernelname=Mackay_kernel
kernelversion=0.70

#****************************************************************
## Checkout correct recovery:
cd ~/android/system/bootable/recovery
git checkout mackay

#****************************************************************
## Set kernel version in buildscript:
cd ~/android/system/buildscripts
git checkout mackay
sed "/Mackay/c\NAME=`echo $kernelname`_`echo $kernelversion`" ~/android/system/buildscripts/samsung/build.sh > ~/android/system/buildscripts/samsung/build.rename
mv ~/android/system/buildscripts/samsung/build.rename ~/android/system/buildscripts/samsung/build.sh
chmod +x ~/android/system/buildscripts/samsung/build.sh
git add samsung/build.sh
git commit -m "Bump kernel version to `echo $kernelversion`"
cd ~/android/system/

#****************************************************************
## Set kernel version in init:
cd ~/android/system/kernel/samsung/aries
git checkout mackay
sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`")\"" ~/android/system/kernel/samsung/aries/init/version.c > ~/android/system/kernel/samsung/aries/init/version.vc
mv ~/android/system/kernel/samsung/aries/init/version.vc ~/android/system/kernel/samsung/aries/init/version.c
git add init/version.c
git commit -m "Bump kernel version to `echo $kernelversion`"
cd ~/android/system/

#****************************************************************
## Set ROM version in common.mk:
cd ~/android/system/vendor/cm
sed "/Mackay/c\    CM_VERSION := `echo $romname`_`echo $romversion`" ~/android/system/vendor/cm/config/common.mk > ~/android/system/vendor/cm/config/common.updated
mv ~/android/system/vendor/cm/config/common.updated ~/android/system/vendor/cm/config/common.mk
git add config/common.mk
git commit -m "Bump ROM version to `echo $romversion`"
cd ~/android/system/

#****************************************************************
## Clean environment:
make installclean
rm $out/system/build.prop
rm $out/obj/PACKAGING/target_files_intermediates/cm_galaxysmtd-target_files-eng.kasper.zip
rm $out/obj/PACKAGING/target_files_intermediates/cm_galaxysmtd-target_files-eng.kasper/SYSTEM/build.prop

#****************************************************************
## Make the build:
./buildscripts/samsung/build.sh $device

#****************************************************************
## Move the ROM to the final ROM preparation stage:
mv $out/$romname* finalize_build

#****************************************************************
## Execute the final ROM preparation:
cd ~/android/system/finalize_build
rm *.md5sum
echo "Extracting Mackay ROM"
unzip -q $romname* -d MackayExtract
echo "Copying Gapps"
cp -R gapps/system/* MackayExtract/system
echo "Copying updater-script"
cp updater-script_s updater-script
cp updater-script MackayExtract/META-INF/com/google/android
rm updater-script
echo "Repacking Mackay ROM"
cd MackayExtract
zip -qr ../`echo $romname`-`echo $romversion`.zip ./
cd ..
echo "Signing package..."
java -jar $top/out/host/linux-x86/framework/signapk.jar $sec/testkey.x509.pem $sec/testkey.pk8 `echo $romname`-`echo $romversion`.zip `echo $romname`-`echo $romversion`-signed.zip
echo "Copying fininalized build to AndroidFlash directory"
cp `echo $romname`-`echo $romversion`-signed.zip ~/AndroidFlash
cp `echo $romname`-`echo $romversion`-signed.zip ~/android/system/finalize_build/AndroidFinished
echo "Cleaning environment"
rm -r MackayExtract
rm $romname*
cd ~/android/system

#*****************Build other kernel flavours********************

#*************************STOCK/VOODOO***************************
sed "/CONFIG_FB_VOODOO=n/c\CONFIG_FB_VOODOO=y" ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig > ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vc
mv ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vc ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig

sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`_VC")\"" ~/android/system/kernel/samsung/aries/init/version.c > ~/android/system/kernel/samsung/aries/init/version.vc
mv ~/android/system/kernel/samsung/aries/init/version.vc ~/android/system/kernel/samsung/aries/init/version.c

sed "/Mackay/c\NAME=`echo $kernelname`_`echo $kernelversion`_VC" ~/android/system/buildscripts/samsung/build.sh > ~/android/system/buildscripts/samsung/build.rename
mv ~/android/system/buildscripts/samsung/build.rename ~/android/system/buildscripts/samsung/build.sh
chmod +x ~/android/system/buildscripts/samsung/build.sh

./buildscripts/samsung/build.sh $device kernel

#**************************BLN/VOODOO****************************
cd ~/android/system/buildscripts
git reset --hard
git checkout mackay_bln
sed "/Mackay/c\NAME=`echo $kernelname`_`echo $kernelversion`_VC_BLN" ~/android/system/buildscripts/samsung/build.sh > ~/android/system/buildscripts/samsung/build.rename
mv ~/android/system/buildscripts/samsung/build.rename ~/android/system/buildscripts/samsung/build.sh
chmod +x ~/android/system/buildscripts/samsung/build.sh
git add ~/android/system/buildscripts/samsung/build.sh
git commit -m "Bump kernel version to `echo $kernelversion`"
cd ~/android/system/

sed "/CONFIG_GENERIC_BLN=n/c\CONFIG_GENERIC_BLN=y" ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig > ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vcbln
mv ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vcbln ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig

sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`_VC_BLN")\"" ~/android/system/kernel/samsung/aries/init/version.c > ~/android/system/kernel/samsung/aries/init/version.vcbln
mv ~/android/system/kernel/samsung/aries/init/version.vcbln ~/android/system/kernel/samsung/aries/init/version.c

./buildscripts/samsung/build.sh $device kernel

#**************************BLN/STOCK*****************************
sed "/Mackay/c\NAME=`echo $kernelname`_`echo $kernelversion`_BLN" ~/android/system/buildscripts/samsung/build.sh > ~/android/system/buildscripts/samsung/build.rename
mv ~/android/system/buildscripts/samsung/build.rename ~/android/system/buildscripts/samsung/build.sh
chmod +x ~/android/system/buildscripts/samsung/build.sh

sed "/CONFIG_FB_VOODOO=y/c\CONFIG_FB_VOODOO=n" ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig > ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.bln
mv ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.bln ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig

sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`_BLN")\"" ~/android/system/kernel/samsung/aries/init/version.c > ~/android/system/kernel/samsung/aries/init/version.bln
mv ~/android/system/kernel/samsung/aries/init/version.bln ~/android/system/kernel/samsung/aries/init/version.c

./buildscripts/samsung/build.sh $device kernel

#*********************Restore Stock Value************************
cd ~/android/system/buildscripts
git reset --hard
git checkout mackay
cd ~/android/system/

sed "/Mackay/c\NAME=`echo $kernelname`_`echo $kernelversion`" ~/android/system/buildscripts/samsung/build.sh > ~/android/system/buildscripts/samsung/build.rename
mv ~/android/system/buildscripts/samsung/build.rename ~/android/system/buildscripts/samsung/build.sh
chmod +x ~/android/system/buildscripts/samsung/build.sh

sed "/CONFIG_GENERIC_BLN=y/c\CONFIG_GENERIC_BLN=n" ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig > ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.stock
mv ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.stock ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig

sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`")\"" ~/android/system/kernel/samsung/aries/init/version.c > ~/android/system/kernel/samsung/aries/init/version.stock
mv ~/android/system/kernel/samsung/aries/init/version.stock ~/android/system/kernel/samsung/aries/init/version.c

#****************************************************************
## Copy all finished kernels to AndroidFinished folder for ftp upload:
mv $out/Mackay_* ~/android/system/finalize_build/AndroidFinished

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
