#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set basic parameters:
target=$1
out=$2
top=$3
sec=$4
romname=$5
romversion=$6
kernelname=$7
kernelversion=$8

#****************************************************************
## Checkout correct recovery:
cd ~/android/system/bootable/recovery
git checkout mackay

#****************************************************************
## Set kernel version in buildscript:
cd ~/android/system/buildscripts
git checkout mackay
sed "/Mackay/c\NAME=`echo $kernelname`_`echo $kernelversion`" ~/android/system/buildscripts/samsung/build.sh > ~/android/system/buildscripts/samsung/build.rename
mv ~/android/system/buildscripts/samsung/build.rename ~/android/system/buildscripts/samsung/build.sh
chmod +x ~/android/system/buildscripts/samsung/build.sh
git add samsung/build.sh
git commit -m "Bump kernel version to `echo $kernelversion`"

#****************************************************************
## Set kernel version in init:
cd ~/android/system/kernel/samsung/aries
git checkout mackay
sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`")\"" ~/android/system/kernel/samsung/aries/init/version.c > ~/android/system/kernel/samsung/aries/init/version.vc
mv ~/android/system/kernel/samsung/aries/init/version.vc ~/android/system/kernel/samsung/aries/init/version.c
git add init/version.c
git commit -m "Bump kernel version to `echo $kernelversion`"

#****************************************************************
## Set ROM version in common.mk:
cd ~/android/system/vendor/cm
sed "/Mackay/c\    CM_VERSION := `echo $romname`_`echo $romversion`" ~/android/system/vendor/cm/config/common.mk > ~/android/system/vendor/cm/config/common.updated
mv ~/android/system/vendor/cm/config/common.updated ~/android/system/vendor/cm/config/common.mk
git add config/common.mk
git commit -m "Bump ROM version to `echo $romversion`"
cd ~/android/system/

#****************************************************************
## Clean environment:
make installclean
rm $out/system/build.prop
rm $out/obj/PACKAGING/target_files_intermediates/cm_$target-target_files-eng.kasper.zip
rm $out/obj/PACKAGING/target_files_intermediates/cm_$target-target_files-eng.kasper/SYSTEM/build.prop

#****************************************************************
## Make the build:
./buildscripts/samsung/build.sh $target

#****************************************************************
## Finish off the ROM by packing in gapps & updated script:
finalize "${out}" "${top}" "${sec}" "${romname}" "${romversion}"

#****************************************************************
## Move the kernel to the Sync location:
mv $out/$kernelname* ~/android/system/finalize_build/AndroidFinished

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
