#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set basic parameters:
target=$1
out=$2
top=$3
sec=$4
romname=$5
romversion=$6
kernelname=$7
kernelversion=$8

#****************************************************************
## Checkout correct recovery:
cd ~/android/system/bootable/recovery
git checkout mackay

#****************************************************************
## Set kernel version in buildscript:
cd ~/android/system/buildscripts
git checkout mackay
sed "/Mackay/c\NAME=`echo $kernelname`_`echo $kernelversion`" ~/android/system/buildscripts/samsung/build.sh > ~/android/system/buildscripts/samsung/build.rename
mv ~/android/system/buildscripts/samsung/build.rename ~/android/system/buildscripts/samsung/build.sh
chmod +x ~/android/system/buildscripts/samsung/build.sh
git add samsung/build.sh
git commit -m "Bump kernel version to `echo $kernelversion`"
cd ~/android/system/

#****************************************************************
## Set kernel version in init:
cd ~/android/system/kernel/samsung/aries
git checkout mackay
sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`")\"" ~/android/system/kernel/samsung/aries/init/version.c > ~/android/system/kernel/samsung/aries/init/version.vc
mv ~/android/system/kernel/samsung/aries/init/version.vc ~/android/system/kernel/samsung/aries/init/version.c
git add init/version.c
git commit -m "Bump kernel version to `echo $kernelversion`"
cd ~/android/system/

#****************************************************************
## Set ROM version in common.mk:
cd ~/android/system/vendor/cm
sed "/Mackay/c\    CM_VERSION := `echo $romname`_`echo $romversion`" ~/android/system/vendor/cm/config/common.mk > ~/android/system/vendor/cm/config/common.updated
mv ~/android/system/vendor/cm/config/common.updated ~/android/system/vendor/cm/config/common.mk
git add config/common.mk
git commit -m "Bump ROM version to `echo $romversion`"
cd ~/android/system/

#****************************************************************
## Clean environment:
make installclean
rm $out/system/build.prop
rm $out/obj/PACKAGING/target_files_intermediates/cm_galaxysmtd-target_files-eng.kasper.zip
rm $out/obj/PACKAGING/target_files_intermediates/cm_galaxysmtd-target_files-eng.kasper/SYSTEM/build.prop

#****************************************************************
## Make the build:
./buildscripts/samsung/build.sh $target

#****************************************************************
## Finish off the ROM by packing in gapps & updated script:
finalize "${target}" "${out}" "${top}" "${sec}" "${romname}" "${romversion}"

#*****************Build other kernel flavours********************

#*************************STOCK/VOODOO***************************
echo "Buil kernel 2 - stock led & voodoo colour"
sed "/CONFIG_FB_VOODOO=n/c\CONFIG_FB_VOODOO=y" ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig > ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vc
mv ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vc ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig

sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`_VC")\"" ~/android/system/kernel/samsung/aries/init/version.c > ~/android/system/kernel/samsung/aries/init/version.vc
mv ~/android/system/kernel/samsung/aries/init/version.vc ~/android/system/kernel/samsung/aries/init/version.c

sed "/Mackay/c\NAME=`echo $kernelname`_`echo $kernelversion`_VC" ~/android/system/buildscripts/samsung/build.sh > ~/android/system/buildscripts/samsung/build.rename
mv ~/android/system/buildscripts/samsung/build.rename ~/android/system/buildscripts/samsung/build.sh
chmod +x ~/android/system/buildscripts/samsung/build.sh

./buildscripts/samsung/build.sh $target kernel

#**************************BLN/VOODOO****************************
echo "Buil kernel 3 - BLN & voodoo colour"
cd ~/android/system/buildscripts
git reset --hard
git checkout mackay_bln
sed "/Mackay/c\NAME=`echo $kernelname`_`echo $kernelversion`_VC_BLN" ~/android/system/buildscripts/samsung/build.sh > ~/android/system/buildscripts/samsung/build.rename
mv ~/android/system/buildscripts/samsung/build.rename ~/android/system/buildscripts/samsung/build.sh
chmod +x ~/android/system/buildscripts/samsung/build.sh
git add ~/android/system/buildscripts/samsung/build.sh
git commit -m "Bump kernel version to `echo $kernelversion`"
cd ~/android/system/

sed "/CONFIG_GENERIC_BLN=n/c\CONFIG_GENERIC_BLN=y" ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig > ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vcbln
mv ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.vcbln ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig

sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`_VC_BLN")\"" ~/android/system/kernel/samsung/aries/init/version.c > ~/android/system/kernel/samsung/aries/init/version.vcbln
mv ~/android/system/kernel/samsung/aries/init/version.vcbln ~/android/system/kernel/samsung/aries/init/version.c

./buildscripts/samsung/build.sh $target kernel

#**************************BLN/STOCK*****************************
echo "Buil kernel 4 - BLN & stock colour"
sed "/Mackay/c\NAME=`echo $kernelname`_`echo $kernelversion`_BLN" ~/android/system/buildscripts/samsung/build.sh > ~/android/system/buildscripts/samsung/build.rename
mv ~/android/system/buildscripts/samsung/build.rename ~/android/system/buildscripts/samsung/build.sh
chmod +x ~/android/system/buildscripts/samsung/build.sh

sed "/CONFIG_FB_VOODOO=y/c\CONFIG_FB_VOODOO=n" ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig > ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.bln
mv ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.bln ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig

sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`_BLN")\"" ~/android/system/kernel/samsung/aries/init/version.c > ~/android/system/kernel/samsung/aries/init/version.bln
mv ~/android/system/kernel/samsung/aries/init/version.bln ~/android/system/kernel/samsung/aries/init/version.c

./buildscripts/samsung/build.sh $target kernel

#*********************Restore Stock Value************************
echo "Set back to stock values"
cd ~/android/system/buildscripts
git reset --hard
git checkout mackay
cd ~/android/system/

sed "/Mackay/c\NAME=`echo $kernelname`_`echo $kernelversion`" ~/android/system/buildscripts/samsung/build.sh > ~/android/system/buildscripts/samsung/build.rename
mv ~/android/system/buildscripts/samsung/build.rename ~/android/system/buildscripts/samsung/build.sh
chmod +x ~/android/system/buildscripts/samsung/build.sh

sed "/CONFIG_GENERIC_BLN=y/c\CONFIG_GENERIC_BLN=n" ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig > ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.stock
mv ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig.stock ~/android/system/kernel/samsung/aries/arch/arm/configs/cyanogenmod_galaxysmtd_defconfig

sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`")\"" ~/android/system/kernel/samsung/aries/init/version.c > ~/android/system/kernel/samsung/aries/init/version.stock
mv ~/android/system/kernel/samsung/aries/init/version.stock ~/android/system/kernel/samsung/aries/init/version.c

#****************************************************************
## Copy all finished kernels to AndroidFinished folder for ftp upload:
echo "Moving all kernel to AndroidFinished folder"
mv $out/Mackay_* ~/android/system/finalize_build/AndroidFinished

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
