#!/bin/bash
#

#****************************************************************
## Set basic parameters:
device=galaxysmtd
out=~/android/system/out/target/product/$device
name=Mackay_kernel
version=0.73

#****************************************************************
## Checkout correct recovery:
cd ~/android/system/bootable/recovery
git checkout mackay

#****************************************************************
## Checkout correct buildscript & set kernel version:
cd ~/android/system/buildscripts
git checkout mackay
sed "/Mackay/c\NAME=`echo $name`_`echo $version`" ~/android/system/buildscripts/samsung/build.sh > ~/android/system/buildscripts/samsung/build.rename
mv ~/android/system/buildscripts/samsung/build.rename ~/android/system/buildscripts/samsung/build.sh
chmod +x ~/android/system/buildscripts/samsung/build.sh
git add ~/android/system/buildscripts/samsung/build.sh
git commit -m "Bump kernel version to `echo $version`"

#****************************************************************
## Set kernel version in init:
cd ~/android/system/kernel/samsung/aries
git checkout mackay
sed "/Mackay/c\	\" ("`echo $name`_`echo $version`")\"" ~/android/system/kernel/samsung/aries/init/version.c > ~/android/system/kernel/samsung/aries/init/version.vc
mv ~/android/system/kernel/samsung/aries/init/version.vc ~/android/system/kernel/samsung/aries/init/version.c
git add ~/android/system/kernel/samsung/aries/init/version.c
git commit -m "Bump kernel version to `echo $version`"
cd ~/android/system/

#****************************************************************
## Build the kernel:
./buildscripts/samsung/build.sh $device kernel
mv $out/Mackay_* ~/android/system/finalize_build/AndroidFinished
