#!/bin/bash
#

#****************************************************************
## Start timer:
START=$(date +%s)

#****************************************************************
## Set basic parameters here:
device=i9100
out=~/android/system/out/target/product/$device
top=~/android/system
sec=~/android/system/build/target/product/security

romname=Mackay_ROM
romversion=1.3.0_s2
kernelname=Mackay_kernel
kernelversion=1.2

#****************************************************************
## Checkout correct recovery:
cd ~/android/system/bootable/recovery
git checkout mackay

#****************************************************************
## Set kernel version in buildscript:
cd ~/android/system/buildscripts
git checkout $device
sed "/Mackay/c\NAME=`echo $kernelname`_`echo $kernelversion`" ~/android/system/buildscripts/samsung/build.sh > ~/android/system/buildscripts/samsung/build.rename
mv ~/android/system/buildscripts/samsung/build.rename ~/android/system/buildscripts/samsung/build.sh
chmod +x ~/android/system/buildscripts/samsung/build.sh
git add samsung/build.sh
git commit -m "Bump kernel version to `echo $kernelversion`"

#****************************************************************
## Set kernel version in init:
cd ~/android/system/kernel/samsung/smdk4210
sed "/Mackay/c\	\" ("`echo $kernelname`_`echo $kernelversion`")\"" ~/android/system/kernel/samsung/aries/init/version.c > ~/android/system/kernel/samsung/aries/init/version.vc
mv ~/android/system/kernel/samsung/aries/init/version.vc ~/android/system/kernel/samsung/aries/init/version.c
git add init/version.c
git commit -m "Bump kernel version to `echo $kernelversion`"
cd ~/android/system/

#****************************************************************
## Clean environment:
make installclean
rm $out/system/build.prop
rm $out/obj/PACKAGING/target_files_intermediates/cm_$device-target_files-eng.kasper.zip
rm $out/obj/PACKAGING/target_files_intermediates/cm_$device-target_files-eng.kasper/SYSTEM/build.prop

#****************************************************************
## Make the build:
./buildscripts/samsung/build.sh $device

#****************************************************************
## Move the ROM to the final ROM preparation stage:
mv $out/$romname* finalize_build

#****************************************************************
## Execute the final ROM preparation:
cd ~/android/system/finalize_build
rm *.md5sum
echo "Extracting Mackay ROM"
unzip -q $romname* -d MackayExtract
echo "Copying Gapps & removing Gtalk"
cp -R gapps/system/* MackayExtract/system
rm MackayExtract/system/app/Talk.apk
echo "Copying updater-script"
cp updater-script_s2 updater-script
cp updater-script MackayExtract/META-INF/com/google/android
rm updater-script
echo "Repacking Mackay ROM"
cd MackayExtract
zip -qr ../`echo $romname`-`echo $romversion`.zip ./
cd ..
echo "Signing package..."
java -jar $top/out/host/linux-x86/framework/signapk.jar $sec/testkey.x509.pem $sec/testkey.pk8 `echo $romname`-`echo $romversion`.zip `echo $romname`-`echo $romversion`-signed.zip
echo "Copying fininalized build to AndroidFlash directory"
cp `echo $romname`-`echo $romversion`-signed.zip ~/android/system/finalize_build/AndroidFinished
echo "Cleaning environment"
rm -r MackayExtract
rm $romname*
cd ~/android/system

#****************************************************************
## Move the kernel to the Sync location:
mv $out/$kernelname* ~/android/system/finalize_build/AndroidFinished

#****************************************************************
## Report timer:
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
printf "${txtgrn}Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n ${txtrst}" $E_SEC
