#!/bin/bash
#

#****************************************************************
## Set basic parameters:
trgt=$1
finalout=$2
androidtop=$3
secsign=$4
name=$5
version=$6

#****************************************************************
## Clean build environment:
cd ~/android/system
make installclean
rm $finalout/boot.img

#****************************************************************
## Build the kernel:
cd ~/android/system/
. build/envsetup.sh
breakfast galaxysmtd
mka bootimage

#****************************************************************
## Finish off the kernel by packing it in a zip:
light=stock
colour=cmc
finalize-kernel "${trgt}" "${finalout}" "${androidtop}" "${secsign}" "${name}" "${version}" "${light}" "${colour}"
